name: student_system_flutter
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  http: "^0.11.3+16"
  local_auth: "^0.2.0"
  cached_network_image: "^0.4.1+1"
  shared_preferences: "^0.4.2"
  flutter_circular_chart: "^0.0.3"
  carousel: "^0.1.0"
  path_provider: "^0.4.1"
  simple_permissions: "^0.1.5"
  font_awesome_flutter: "^7.0.0"
  image_picker: "^0.4.5"
  rxdart: "^0.18.0"
  mime: ^0.9.6
  url_launcher: ^3.0.3
  google_maps_flutter:
   git:
     url: git://github.com/flutter/plugins
     path: packages/google_maps_flutter
  flutter_map: ^0.0.10

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/file_manager_icons/

    - assets/fonts/CupertinoIcons.ttf

  fonts:
    - family: CuperIcon
      fonts:
        - asset: assets/fonts/CupertinoIcons.ttf
    - family: OpenSansCondensedLight
      fonts:
        - asset: assets/fonts/OpenSansCondensedLight.ttf
    - family: RalewayRegular
      fonts:
        - asset: assets/fonts/RalewayRegular.ttf
    - family: SlaboRegular
      fonts:
        - asset: assets/fonts/SlaboRegular.ttf
