name: student_system_flutter
description: WIUT Intranet

dependencies:
  flutter:
    sdk: flutter
  http: "^0.11.3+16"
  local_auth: "^0.2.0"
  cached_network_image: "^0.4.1+1"
  shared_preferences: "^0.4.2"
  flutter_circular_chart: "^0.0.3"
  # carousel: "^0.1.0"
  path_provider: "^0.4.1"
  simple_permissions: "^0.1.5"
  font_awesome_flutter: "^7.0.0"
  image_picker: "^0.4.5"
  rxdart: "^0.18.0"
  mime: ^0.9.6
  # asynchronous_validator: ^1.0.2
  url_launcher: ^3.0.3
  flutter_map: ^0.0.10
  flushbar: ^0.7.5
  package_info: ^0.3.2
  # flutter_launcher_icons: ^0.6.0

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_launcher_icons: ^0.6.0
  community_material_icon: ^0.1.2
  connectivity: ^0.3.1

# flutter_icons:
#   android: true 
#   # ios: "Example-Icon"
#   image_path: "assets/icon.png"
#   image_path_android: "assets/icon.png"
#   # image_path_ios: "assets/icon/icon_ios.png"
#   adaptive_icon_background: "#FF0091ea"
#   # adaptive_icon_foreground: "assets/icon/icon-foreground.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/file_manager_icons/

    - assets/fonts/CupertinoIcons.ttf

  fonts:
    - family: CuperIcon
      fonts:
        - asset: assets/fonts/CupertinoIcons.ttf
    - family: OpenSansCondensedLight
      fonts:
        - asset: assets/fonts/OpenSansCondensedLight.ttf
    - family: RalewayRegular
      fonts:
        - asset: assets/fonts/RalewayRegular.ttf
    - family: SlaboRegular
      fonts:
        - asset: assets/fonts/SlaboRegular.ttf
