name: student_system_flutter
description: WIUT Intranet

dependencies:
  flutter:
    sdk: flutter 
  http: "^0.11.3+16"
  local_auth: "^0.2.0"
  cached_network_image: "^0.4.2"
  shared_preferences: "^0.4.2"
  path_provider: "^0.4.1"
  simple_permissions: "^0.1.6"
  font_awesome_flutter: "^8.0.1"
  image_picker: "^0.4.5"
  rxdart: "^0.18.0"
  mime: ^0.9.6
  sentry: ^2.1.0
  url_launcher: ^3.0.3
  flushbar: ^0.8.2
  package_info: ^0.3.2
  connectivity: ^0.3.1
  # open_file: ^1.0.7
  flutter_sound: ^1.1.1
  # screen: ^0.0.4
  # flutter_circular_chart: "^0.1.0"
  # flutter_map: ^0.1.1
  screen: ^0.0.3
  flutter_map: ^0.0.11+1
  flutter_circular_chart: "^0.0.3"
  open_file:
    git:
      url: git://github.com/daniel-mf/open_file.git
  
  # flutter_advanced_networkimage: ^0.3.8
  # carousel: "^0.1.0"

  material_design_icons_flutter: ^2.7.94
  # community_material_icon: ^0.1.2

  cupertino_icons: ^0.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # flutter_launcher_icons: ^0.6.1
  flutter_launcher_icons: ^0.5.2
  
  # carousel_pro: ^0.0.13

flutter_icons:
  android: true 
  ios: "AppIcon"
  image_path: "assets/icon.png"
  image_path_android: "assets/icon.png"
  image_path_ios: "assets/icon.png"
  adaptive_icon_background: "#FF0091ea"
  # adaptive_icon_foreground: "assets/icon/icon-foreground.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/file_manager_icons/
    - assets/player/
    - assets/fonts/CupertinoIcons.ttf

  fonts:
    - family: CuperIcon
      fonts:
        - asset: assets/fonts/CupertinoIcons.ttf
    - family: OpenSansCondensedLight
      fonts:
        - asset: assets/fonts/OpenSansCondensedLight.ttf
    - family: RalewayRegular
      fonts:
        - asset: assets/fonts/RalewayRegular.ttf
    - family: SlaboRegular
      fonts:
        - asset: assets/fonts/SlaboRegular.ttf
